ONERMELER = {}


def N(id, metin, tur, kat, aile='', zayif=0, not_=''):
    ONERMELER[id] = dict(id=id, metin=metin, tur=tur, kat=kat, aile=aile, zayif=zayif, not_=not_)


N('e_celismezlik', 'Bir şey aynı bakımdan hem var hem yok olamaz (çelişmezlik).', 'evveliyyat', 'yakîn')
N('e_ucuncu_sik', 'Bir şey ya vardır ya yoktur; üçüncü şık yoktur.', 'evveliyyat', 'yakîn')
N('m_ben', 'Şüphe eden ve düşünen en az bir şey vardır (şüphe edenin kendi varlığı inkâr edilemez).', 'musahede', 'yakîn', not_='vicdâniyyât (I.3.3.2)')
N('m_degisim', 'Âlemde değişen şeyler vardır.', 'musahede', 'yakîn')
N('m_cok', 'Âlemde çokluk ve farklılık vardır.', 'musahede', 'yakîn')
N('m_mumkin', 'Âlemde varlığı zâtının gereği olmayan (başka türlü olması düşünülebilen) şeyler vardır.', 'musahede', 'yakîn')
N('m_tahsis', 'Âlemdeki her şey birçok mümkin hâlden yalnız birindedir (belirli büyüklük, yer ve özellikte bulunur).', 'musahede', 'yakîn')
N('m_nizam', 'Âlemde düzenli kanunlar ve yaşama elverişli ince sabitler vardır.', 'musahede', 'yakîn', not_='varlığı müşâhededir; sebebi hakkındaki çıkarım zan-ı gâliptir')
N('m_ihkam', 'Âlemde amaca uygun ve ince ayarlı (muhkem) eserler vardır.', 'musahede', 'yakîn')
N('m_bilinc', 'İnsanda bilinç, ahlâkî hüküm ve anlam arayışı vardır.', 'musahede', 'yakîn')
N('t_vacib', 'Vâcib: varlığı kendi zâtından olan, yokluğu imkânsız olandır.', 'tanim', 'yakîn')
N('t_mumkin', 'Mümkin: varlığı da yokluğu da kendi zâtından gerekmeyendir.', 'tanim', 'yakîn')
N('t_alem', 'Âlem: Vâcib dışında kalan bütün mevcutların bütünüdür.', 'tanim', 'yakîn')
N('t_cisim', 'Cisim: uzayda yer tutan, parçalara bölünebilen, hareket ve durgunluk gibi arazlar kabul eden şeydir.', 'tanim', 'yakîn', not_='felsefecilerin madde–sûret tarifi başkadır; tanım muhatapla ortaklaştırılır (I.2.3)')
N('t_hulul', 'Hulûl: bir şeyin başka bir şeyde (mahalde) yerleşmesidir.', 'tanim', 'yakîn')
N('t_ittihad', 'İttihâd: iki ayrı şeyin bir olmasıdır.', 'tanim', 'yakîn')
N('k_muhtac_mumkin', 'Herhangi bir bakımdan başkasına muhtaç olan mümkindir; Vâcib hiçbir bakımdan muhtaç olamaz.', 'mantik', 'yakîn', not_='tanımdan türer')
N('k_parca_muhtac', 'Parçalardan oluşan şey parçalarına muhtaçtır; muhtaç olan mümkindir.', 'mantik', 'yakîn')
N('k_degisen_vacib_degil', 'Değişen (bir hâlini yitiren) şey vâcib olamaz: yitirilen hâl için yokluk mümkündür.', 'mantik', 'yakîn')
N('k_aciz_vacib_degil', 'Aciz olan (bir şeye gücü yetmeyen) vâcib olamaz; güç yetmemek bir şarta veya başkasına muhtaçlıktır.', 'mantik', 'yakîn')
N('k_ittihad_imkansiz', 'İki ayrı şey ayrı olarak devam ederken bir olamaz; biri yok olursa ittihâd değil yok oluştur.', 'mantik', 'yakîn')
N('k_hulul_muhtac', 'Bir mahalde yerleşen (hâl) mahalle muhtaçtır.', 'mantik', 'yakîn')
N('k_devir_imkansiz', 'Bir şey kendi sebebinin sebebi olamaz: aynı şey aynı bakımdan hem önce hem sonra olurdu.', 'mantik', 'yakîn')
N('k_cisim_parcali', 'Cisim parçalıdır ve hareket ile durgunluktan hâlî olmaz.', 'mantik', 'yakîn', not_='cisim tanımından türer')
N('k_hadis_muhdis', 'Var olmaya başlayan (hâdis) her şeyin bir muhdisi vardır.', 'turetilmis', 'yakîn', 'sebep-ilkesi-varlik', 2, 'evveliyyât sayımı tartışmalıdır (V.0 tenkit); Hume ve kuantum itirazlarının hedefidir (V.1.4)')
N('k_tercihsiz', 'Var olmasıyla olmaması eşit imkânda olan şeyin var olması bir müreccihe muhtaçtır (tercihsiz tercih imkânsızdır).', 'turetilmis', 'yakîn', 'sebep-ilkesi-varlik', 1, 'V.1.3.b.4: yeter sebep ilkesinin VARLIK kanadı (yokluk ile varlık eşit imkânda ise varlık bir müreccih ister); en zayıf halkalardan biri (V.9.2)')
N('k_tercihsiz_hal', 'Eşit imkânlı birden çok hâlden yalnız birinin gerçekleşmesi (tahsis) bir müreccihe muhtaçtır.', 'turetilmis', 'yakîn', 'sebep-ilkesi-hal', 1, 'yeter sebep ilkesinin HÂL kanadı; rastgelelik itirazının (kuantum, kura, zar) asıl hedefi budur')
N('k_sonsuz_hadis', 'Geçmişte sonsuz bir hâdis dizisi bulunamaz.', 'turetilmis', 'yakîn', 'sonsuz-gecmis', 1, 'V.1.3.a.3: en zayıf halka; ardışık sonsuzun imkânına dair ihtilaf vardır')
N('k_terkip', 'Mümkinlerin bütünü, parçaları gibi mümkindir; bütün, parçalarından ayrı bir vâcib olamaz.', 'turetilmis', 'yakîn', 'terkip', 1, 'V.1.3.b.7–8: terkip safsatası itirazına cevap')
N('k_kemal', 'Varlıkta bir kemâl varsa onu veren Vâcib o kemâlden mahrum olamaz.', 'turetilmis', 'yakîn', 'kemal', 1, 'V.2.2.5: ilke, ispat değil; en zayıf halkalardan')
N('k_gaye', 'Gâyesiz fiil kemâle ters düşer.', 'turetilmis', 'zan-ı gâlib', 'kemal', 1, 'V.2.4.1')
N('k_ozdes', 'Her bakımdan ayırt edilemeyen iki şey tektir.', 'turetilmis', 'yakîn', 'ozdes', 1, 'V.2.1.4: özdeşlerin ayrımsızlığı felsefede tartışmalıdır (V.2 tenkit)')
N('k_zihni_parca', 'Zihnen ayrılan iki mâna (ortak mahiyet ve ayırıcı, yahut mahiyet ve vücûd) Vâcib’de gerçek bir terkip doğurur ve terkip muhtaçlıktır.', 'turetilmis', 'zan-ı gâlib', 'zihni-parca', 1, 'zihnî ayrımın hâricî terkibe delâleti tartışmalıdır')
N('k_mekan_cisim', 'Bir yönde ve mekânda bulunan şey cisimdir veya cisimde kâim arazdır.', 'turetilmis', 'zan-ı gâlib', 'mekan', 1, 'felsefeciler mücerredin mekâna nisbetini başka kurar')
N('k_ihkam_ilim', 'Muhkem (amaca uygun ve ince ayarlı) bir eser, ilimli ve iradeli bir fâile işaret eder.', 'turetilmis', 'zan-ı gâlib', 'ihkam', 2, 'tesadüf ve zorunluluk ihtimalleri ayrıca elenir; çoklu evren itirazı (V.1.4.5)')
N('k_kudret_fiil', 'Var etme fiili kudretsiz olmaz: fâil fiili yapabilen olmalıdır.', 'mantik', 'yakîn')
N('k_irade_ilim', 'İrade, murad edilenin bilinmesini gerektirir (bilmediğini murad edemez).', 'mantik', 'yakîn')
N('k_irade_cuzi', 'İrade belirli (cüz’î) olana taalluk eder: tahsis her zaman bir belirli hâli seçmektir.', 'mantik', 'yakîn')
N('k_zorunlu_sonuc', 'Zorunlu sebebin sonucu da zorunludur (başkasıyla zorunlu, vâcib bi-ğayrihi).', 'mantik', 'yakîn', not_='felsefecilerin sudûr nizamının dayanağı; bu önerme tek başına çelişki doğurmaz')
N('k_aciz_vacib_hayat', 'Hayy: ilim ve kudret sahibidir; ilim ve kudret sahibi olmayan cansızdır.', 'tanim', 'yakîn')
N('k_zat_vucub', 'Vâcib’in mahiyeti (zâtı) vücûdun kendisidir; vücûd zâta ilave bir şey değildir.', 'turetilmis', 'zan-ı gâlib', 'zat-vucud', 1, 'İbn Sînâ çizgisinin ilkesi; hafızadan, yoklanmadı')
N('k_sebep_istemez', 'Sebep ihtiyacı mümkine mahsustur; Vâcib’de sebep sorusu tanımına aykırıdır.', 'mantik', 'yakîn')
N('k_sibr_sebep', 'Bir şeyin açıklaması ya vardır ya yoktur; varsa ya zâtındandır ya zâtı dışındandır.', 'mantik', 'yakîn', not_='nefy–isbât')
N('k_butunun_dis_muhtac', 'Bütünün varlığı, parçalarının varlığından ibaret olduğundan, bütün için bütünün dışında bir müreccih ya yoktur ya vâciptir.', 'turetilmis', 'yakîn', 'terkip', 1, 'parçadan bütüne geçiş terkip safsatası itirazına açıktır (V.1.3.b.7–8)')
N('k_kendi_kendine', 'Bir şey kendi varlığına sebep olmak için önce var olmalıdır (kendi kendinin sebebi olamaz).', 'mantik', 'yakîn')
N('k_cokluk_terkip', 'İki vâcib birbirinden ayrılıyorsa her birinde ortak (vâcib olma) ve ayırıcı iki ayrı mâna vardır; bu terkiptir.', 'turetilmis', 'zan-ı gâlib', 'zihni-parca', 1)
N('k_sinirli_mumkin', 'Sınırlı olan, sınırını zâtından alamaz (başka bir sınır da mümkün); sınırı bir müreccihle belirlenir.', 'turetilmis', 'yakîn', 'sebep-ilkesi-hal', 1)
N('k_muhtac_ibadet', 'Varlığını başkasından alan şey, kendisine nihaî bağlılık (ibadet) borçlu olunacak olan değildir; nihaî bağlılık, varlığı ve nimeti kendinden olana aittir.', 'turetilmis', 'zan-ı gâlib', 'ibadet-tanimi', 1, 'ibadetin tanımı muhatapla ortaklaştırılmalıdır')
N('k_sebepsiz_bilgi', 'Sebepsiz hâdis imkânı kabul edilirse hiçbir ilmî açıklamanın ve ispatın temeli kalmaz.', 'turetilmis', 'zan-ı gâlib', 'sebep-ilkesi-bilgi', 2)
N('k_zaman_vacib_degil', 'Zaman değişimin ölçüsüdür ve mümkine aittir; Vâcib zamanla (önce–sonra ile) sınırlanmaz.', 'turetilmis', 'zan-ı gâlib', 'zaman', 1)
N('k_ilim_degisim', 'Sonradan bir şey öğrenen değişir; değişen vâcib olamaz.', 'mantik', 'yakîn')
N('k_hasir_cevap_uzayi', 'Cevap uzayı aklî hasırla kurulmuşsa bütün yanlış hücrelerin reddi kalan hücreyi ispatlar.', 'mantik', 'yakîn')
N('k_sebepsiz_bagimsiz', 'Sebepsizliği savunan, savunmasında bir gerekçe getirir; gerekçe getirmek açıklama aramaktır.', 'mantik', 'zan-ı gâlib', 'sebep-ilkesi-bilgi', 2)
N('k_bilinemez_bilgi', '“Bilinemez” hükmü bilgi iddiasıdır; hükmü veren bunu bildiğini söyler.', 'mantik', 'yakîn')
N('k_hakikat_hakikat', '“Hakikat yoktur” cümlesi hakikat iddiasıdır; “hakikat kişiye göredir” cümlesi herkes için doğru olmayı ister.', 'mantik', 'yakîn')
N('k_zorunluluk_dicto', 'Zorunluluğu yalnız önermelere ait sayıp varlıklara ait saymamak, kip mantığında bir tercihtir; ispat edilmiş bir teorem değildir.', 'mantik', 'zan-ı gâlib', '', 1, 'Quine ve Findlay çizgisi; hafızadan, yoklanmadı')
N('k_zat_vacip_tutarli', 'Tanımın parçaları (varlık, zâtından olmak, yokluğu imkânsız olmak) arasında çelişki bulunmaz.', 'mantik', 'yakîn', not_='tanım tahlilinin neticesi; muhatapla ortak tanım gerekir')
N('k_basit_vacib', 'Vâcib’in parçası olsaydı parçalarına muhtaç olurdu; muhtaç olan mümkindir.', 'mantik', 'yakîn')
N('k_hudus_cisim', 'Cisim hareket ve durgunluk arazlarından hâlî olmaz; arazlardan hâlî olmayan hâdistir.', 'turetilmis', 'yakîn', 'sonsuz-gecmis', 1, 'sonsuz hâdis dizisi imkânsızlığına bağlıdır')
N('k_sonsuz_vacib', 'Sonsuz sayıda vâcib, her ikisini ikili olarak alınca iki vâcib sorununa iner.', 'mantik', 'yakîn')
N('k_hasir_adet', 'Vâcib sayısı ya sıfırdır ya birdir ya ikiden çoktur.', 'mantik', 'yakîn')
N('k_zorunlu_tanim', 'Zâtından vâcib olanın vücûbunun başka bir sebebi sorulamaz; tanım gereği sebebi zâtıdır.', 'mantik', 'yakîn')
N('k_yalniz_duyu_kendini_yikar', '“Bilgi yalnız duyu verisinden ibarettir” cümlesi duyuyla bilinemez; kendi ölçüsünü karşılamaz.', 'mantik', 'yakîn')
N('k_vuku_imkan', 'Var olan şey olabilir bir şeydir; vukû imkânı gösterir (mümteni olan var olamaz).', 'mantik', 'yakîn')
N('k_cok_vacib_cift', 'Birden fazla vâcib varsa, onlardan herhangi ikisi “iki vâcib” durumunu doğurur.', 'mantik', 'yakîn')
N('k_beka_muhtac', 'Mümkinin varlığının devamı da zâtından olmadığından, devam ettiği her an müreccihe muhtaçtır.', 'turetilmis', 'yakîn', 'sebep-ilkesi-varlik', 1, 'bekâ ihtiyacı kelâm içinde de ihtilaflıdır; hafızadan, yoklanmadı')
N('k_zulum_noksan', 'Zulüm ihtiyaç, cehalet veya acizden doğar; bunlardan hiçbiri Vâcib’de bulunamaz.', 'turetilmis', 'zan-ı gâlib', 'kemal', 1, 'zulmün tanımı muhatapla ortaklaştırılmalıdır (V.2.4.2)')
N('k_yalan_noksan', 'Yalan cehalet, acz veya ihtiyaçtan doğar; bunlardan hiçbiri Vâcib’de bulunamaz.', 'turetilmis', 'zan-ı gâlib', 'kemal', 1, 'yalanın tanımı muhatapla ortaklaştırılmalıdır')
N('k_hucre_dislama', 'Aynı suâlin hücreleri aklî hasırla birbirini dışlar: biri doğruysa öbürleri yanlıştır.', 'mantik', 'yakîn')
