ONERMELER = {}


def N(id, metin, tur, kat, aile='', zayif=0, not_=''):
    ONERMELER[id] = dict(id=id, metin=metin, tur=tur, kat=kat, aile=aile, zayif=zayif, not_=not_)


N('e_celismezlik', 'Bir şey aynı bakımdan hem var hem yok olamaz (çelişmezlik).', 'evveliyyat', 'yakîn')
N('e_ucuncu_sik', 'Bir şey ya vardır ya yoktur; üçüncü şık yoktur.', 'evveliyyat', 'yakîn')
N('m_ben', 'Şüphe eden ve düşünen en az bir şey vardır (şüphe edenin kendi varlığı inkâr edilemez).', 'musahede', 'yakîn', not_='vicdâniyyât (I.3.3.2)')
N('m_degisim', 'Âlemde değişen şeyler vardır.', 'musahede', 'yakîn')
N('m_cok', 'Âlemde çokluk ve farklılık vardır.', 'musahede', 'yakîn')
N('m_mumkin', 'Âlemde varlığı zâtının gereği olmayan (başka türlü olması düşünülebilen) şeyler vardır.', 'musahede', 'yakîn')
N('m_tahsis', 'Âlemdeki her şey birçok mümkin hâlden yalnız birindedir (belirli büyüklük, yer ve özellikte bulunur).', 'musahede', 'yakîn')
N('m_nizam', 'Âlemde düzenli kanunlar ve yaşama elverişli ince sabitler vardır.', 'musahede', 'yakîn', not_='varlığı müşâhededir; sebebi hakkındaki çıkarım zan-ı gâliptir')
N('m_ihkam', 'Âlemde amaca uygun ve ince ayarlı (muhkem) eserler vardır.', 'musahede', 'yakîn')
N('m_bilinc', 'İnsanda bilinç, ahlâkî hüküm ve anlam arayışı vardır.', 'musahede', 'yakîn')
N('t_vacib', 'Vâcib: varlığı kendi zâtından olan, yokluğu imkânsız olandır.', 'tanim', 'yakîn')
N('t_mumkin', 'Mümkin: varlığı da yokluğu da kendi zâtından gerekmeyendir.', 'tanim', 'yakîn')
N('t_alem', 'Âlem: Vâcib dışında kalan bütün mevcutların bütünüdür.', 'tanim', 'yakîn')
N('t_cisim', 'Cisim: uzayda yer tutan, parçalara bölünebilen, hareket ve durgunluk gibi arazlar kabul eden şeydir.', 'tanim', 'yakîn', not_='felsefecilerin madde–sûret tarifi başkadır; tanım muhatapla ortaklaştırılır (I.2.3)')
N('t_hulul', 'Hulûl: bir şeyin başka bir şeyde (mahalde) yerleşmesidir.', 'tanim', 'yakîn')
N('t_ittihad', 'İttihâd: iki ayrı şeyin bir olmasıdır.', 'tanim', 'yakîn')
N('k_muhtac_mumkin', 'Herhangi bir bakımdan başkasına muhtaç olan mümkindir; Vâcib hiçbir bakımdan muhtaç olamaz.', 'mantik', 'yakîn', not_='tanımdan türer')
N('k_parca_muhtac', 'Parçalardan oluşan şey parçalarına muhtaçtır; muhtaç olan mümkindir.', 'mantik', 'yakîn')
N('k_degisen_vacib_degil', 'Değişen (bir hâlini yitiren) şey vâcib olamaz: yitirilen hâl için yokluk mümkündür.', 'mantik', 'yakîn')
N('k_aciz_vacib_degil', 'Aciz olan (bir şeye gücü yetmeyen) vâcib olamaz; güç yetmemek bir şarta veya başkasına muhtaçlıktır.', 'mantik', 'yakîn')
N('k_ittihad_imkansiz', 'İki ayrı şey ayrı olarak devam ederken bir olamaz; biri yok olursa ittihâd değil yok oluştur.', 'mantik', 'yakîn')
N('k_hulul_muhtac', 'Bir mahalde yerleşen (hâl) mahalle muhtaçtır.', 'mantik', 'yakîn')
N('k_devir_imkansiz', 'Bir şey kendi sebebinin sebebi olamaz: aynı şey aynı bakımdan hem önce hem sonra olurdu.', 'mantik', 'yakîn')
N('k_cisim_parcali', 'Cisim parçalıdır ve hareket ile durgunluktan hâlî olmaz.', 'mantik', 'yakîn', not_='cisim tanımından türer')
N('k_hadis_muhdis', 'Var olmaya başlayan (hâdis) her şeyin bir muhdisi vardır.', 'turetilmis', 'yakîn', 'sebep-ilkesi-varlik', 2, 'evveliyyât sayımı tartışmalıdır (V.0 tenkit); Hume ve kuantum itirazlarının hedefidir (V.1.4)')
N('k_tercihsiz', 'Var olmasıyla olmaması eşit imkânda olan şeyin var olması bir müreccihe muhtaçtır (tercihsiz tercih imkânsızdır).', 'turetilmis', 'yakîn', 'sebep-ilkesi-varlik', 1, 'V.1.3.b.4: yeter sebep ilkesinin VARLIK kanadı (yokluk ile varlık eşit imkânda ise varlık bir müreccih ister); en zayıf halkalardan biri (V.9.2); padişah kararı (3-I 239): şimdilik evvelî ilan edilmiştir, katiyet işareti yükseltilmemiştir; kelâmda ontolojik anlamı “mûcidsiz icâd muhaldir”dir (Sadrüşşerîa; Güldü 2022, s.590-592)')
N('k_tercihsiz_hal', 'Eşit imkânlı birden çok hâlden yalnız birinin gerçekleşmesi (tahsis) bir müreccihe (bir fâilin iradesi dâhil) muhtaçtır.', 'turetilmis', 'yakîn', 'sebep-ilkesi-hal', 1, 'yeter sebep ilkesinin HÂL kanadı; rastgelelik itirazının (kuantum, kura, zar) asıl hedefi budur; padişah kararı (3-I 239): şimdilik evvelî ilan edilmiştir; klasik kelâm hâl seçimi için fâil-i muhtâr iradeyi müreccih sayar ve iradenin kendi tercihi için ikinci müreccih aramaz, bu önerme klasik ilkeden GENİŞTİR (DESTEK/SEBEP_ILKESI_ARASTIRMA.md)')
N('k_sonsuz_hadis', 'Geçmişte sonsuz bir hâdis dizisi bulunamaz.', 'turetilmis', 'yakîn', 'sonsuz-gecmis', 1, 'V.1.3.a.3: en zayıf halka; ardışık sonsuzun imkânına dair ihtilaf vardır')
N('k_terkip', 'Mümkinlerin bütünü, parçaları gibi mümkindir; bütün, parçalarından ayrı bir vâcib olamaz.', 'turetilmis', 'yakîn', 'terkip', 1, 'V.1.3.b.7–8: terkip safsatası itirazına cevap')
N('k_kemal', 'Varlıkta bir kemâl varsa onu veren Vâcib o kemâlden mahrum olamaz.', 'turetilmis', 'yakîn', 'kemal', 1, 'V.2.2.5: ilke, ispat değil; en zayıf halkalardan')
N('k_gaye', 'Gâyesiz fiil kemâle ters düşer.', 'turetilmis', 'zan-ı gâlib', 'kemal', 1, 'V.2.4.1')
N('k_ozdes', 'Her bakımdan ayırt edilemeyen iki şey tektir.', 'turetilmis', 'yakîn', 'ozdes', 1, 'V.2.1.4: özdeşlerin ayrımsızlığı felsefede tartışmalıdır (V.2 tenkit)')
N('k_zihni_parca', 'Zihnen ayrılan iki mâna (ortak mahiyet ve ayırıcı, yahut mahiyet ve vücûd) Vâcib’de gerçek bir terkip doğurur ve terkip muhtaçlıktır.', 'turetilmis', 'zan-ı gâlib', 'zihni-parca', 1, 'zihnî ayrımın hâricî terkibe delâleti tartışmalıdır')
N('k_mekan_cisim', 'Bir yönde ve mekânda bulunan şey cisimdir veya cisimde kâim arazdır.', 'turetilmis', 'zan-ı gâlib', 'mekan', 1, 'felsefeciler mücerredin mekâna nisbetini başka kurar')
N('k_ihkam_ilim', 'Muhkem (amaca uygun ve ince ayarlı) bir eser, ilimli ve iradeli bir fâile işaret eder.', 'turetilmis', 'zan-ı gâlib', 'ihkam', 2, 'tesadüf ve zorunluluk ihtimalleri ayrıca elenir; çoklu evren itirazı (V.1.4.5)')
N('k_kudret_fiil', 'Var etme fiili kudretsiz olmaz: fâil fiili yapabilen olmalıdır.', 'mantik', 'yakîn')
N('k_irade_ilim', 'İrade, murad edilenin bilinmesini gerektirir (bilmediğini murad edemez).', 'mantik', 'yakîn')
N('k_irade_cuzi', 'İrade belirli (cüz’î) olana taalluk eder: tahsis her zaman bir belirli hâli seçmektir.', 'mantik', 'yakîn')
N('k_zorunlu_sonuc', 'Zorunlu sebebin sonucu da zorunludur (başkasıyla zorunlu, vâcib bi-ğayrihi).', 'mantik', 'yakîn', not_='felsefecilerin sudûr nizamının dayanağı; bu önerme tek başına çelişki doğurmaz')
N('k_aciz_vacib_hayat', 'Hayy: ilim ve kudret sahibidir; ilim ve kudret sahibi olmayan cansızdır.', 'tanim', 'yakîn')
N('k_zat_vucub', 'Vâcib’in mahiyeti (zâtı) vücûdun kendisidir; vücûd zâta ilave bir şey değildir.', 'turetilmis', 'zan-ı gâlib', 'zat-vucud', 1, 'İbn Sînâ çizgisinin ilkesi; hafızadan, yoklanmadı')
N('k_sebep_istemez', 'Vâcib’in vücûbunun ayrı bir sebebi aranmaz: Vâcib’de sebep sorusu tanımına aykırıdır.', 'mantik', 'yakîn', not_='ESKİ METİN “sebep ihtiyacı mümkine mahsustur” idi ve “her mümkin sebep ister” yönünü yakîn öncül olarak gizlice taşıyordu; bu yön tartışmalı ilkenin (müreccih) kendisidir ve artık yalnız k_tercihsiz / k_tercihsiz_hal olarak, zayıf işaretli girer (PRUSS_G11_EZELI_MUMKIN.md)')
N('k_sibr_sebep', 'Bir şeyin açıklaması ya vardır ya yoktur; varsa ya zâtındandır ya zâtı dışındandır.', 'mantik', 'yakîn', not_='nefy–isbât')
N('k_butunun_dis_muhtac', 'Bütünün varlığı, parçalarının varlığından ibaret olduğundan, bütün için bütünün dışında bir müreccih ya yoktur ya vâciptir.', 'turetilmis', 'yakîn', 'terkip', 1, 'parçadan bütüne geçiş terkip safsatası itirazına açıktır (V.1.3.b.7–8)')
N('k_kendi_kendine', 'Bir şey kendi varlığına sebep olmak için önce var olmalıdır (kendi kendinin sebebi olamaz).', 'mantik', 'yakîn')
N('k_cokluk_terkip', 'İki vâcib birbirinden ayrılıyorsa her birinde ortak (vâcib olma) ve ayırıcı iki ayrı mâna vardır; bu terkiptir.', 'turetilmis', 'zan-ı gâlib', 'zihni-parca', 1)
N('k_sinirli_mumkin', 'Sınırlı olan, sınırını zâtından alamaz (başka bir sınır da mümkün); sınırı bir müreccihle belirlenir.', 'turetilmis', 'yakîn', 'sebep-ilkesi-hal', 1)
N('k_muhtac_ibadet', 'Varlığını başkasından alan şey, kendisine nihaî bağlılık (ibadet) borçlu olunacak olan değildir; nihaî bağlılık, varlığı ve nimeti kendinden olana aittir.', 'turetilmis', 'zan-ı gâlib', 'ibadet-tanimi', 1, 'ibadetin tanımı muhatapla ortaklaştırılmalıdır')
N('k_sebepsiz_bilgi', 'Sebepsiz hâdis imkânı kabul edilirse hiçbir ilmî açıklamanın ve ispatın temeli kalmaz.', 'turetilmis', 'zan-ı gâlib', 'sebep-ilkesi-bilgi', 2)
N('k_zaman_vacib_degil', 'Zaman değişimin ölçüsüdür ve mümkine aittir; Vâcib zamanla (önce–sonra ile) sınırlanmaz.', 'turetilmis', 'zan-ı gâlib', 'zaman', 1)
N('k_ilim_degisim', 'Sonradan bir şey öğrenen değişir; değişen vâcib olamaz.', 'mantik', 'yakîn')
N('k_hasir_cevap_uzayi', 'Cevap uzayı aklî hasırla kurulmuşsa bütün yanlış hücrelerin reddi kalan hücreyi ispatlar.', 'mantik', 'yakîn')
N('k_sebepsiz_bagimsiz', 'Sebepsizliği savunan, savunmasında bir gerekçe getirir; gerekçe getirmek açıklama aramaktır.', 'mantik', 'zan-ı gâlib', 'sebep-ilkesi-bilgi', 2)
N('k_bilinemez_bilgi', '“Bilinemez” hükmü bilgi iddiasıdır; hükmü veren bunu bildiğini söyler.', 'mantik', 'yakîn')
N('k_hakikat_hakikat', '“Hakikat yoktur” cümlesi hakikat iddiasıdır; “hakikat kişiye göredir” cümlesi herkes için doğru olmayı ister.', 'mantik', 'yakîn')
N('k_zorunluluk_dicto', 'Zorunluluğu yalnız önermelere ait sayıp varlıklara ait saymamak, kip mantığında bir tercihtir; ispat edilmiş bir teorem değildir.', 'mantik', 'zan-ı gâlib', '', 1, 'Quine ve Findlay çizgisi; hafızadan, yoklanmadı')
N('k_zat_vacip_tutarli', 'Tanımın parçaları (varlık, zâtından olmak, yokluğu imkânsız olmak) arasında çelişki bulunmaz.', 'mantik', 'yakîn', not_='tanım tahlilinin neticesi; muhatapla ortak tanım gerekir')
N('k_basit_vacib', 'Vâcib’in parçası olsaydı parçalarına muhtaç olurdu; muhtaç olan mümkindir.', 'mantik', 'yakîn')
N('k_hudus_cisim', 'Cisim hareket ve durgunluk arazlarından hâlî olmaz; arazlardan hâlî olmayan hâdistir.', 'turetilmis', 'yakîn', 'sonsuz-gecmis', 1, 'sonsuz hâdis dizisi imkânsızlığına bağlıdır')
N('k_sonsuz_vacib', 'Sonsuz sayıda vâcib, her ikisini ikili olarak alınca iki vâcib sorununa iner.', 'mantik', 'yakîn')
N('k_hasir_adet', 'Vâcib sayısı ya sıfırdır ya birdir ya ikiden çoktur.', 'mantik', 'yakîn')
N('k_zorunlu_tanim', 'Zâtından vâcib olanın vücûbunun başka bir sebebi sorulamaz; tanım gereği sebebi zâtıdır.', 'mantik', 'yakîn')
N('k_yalniz_duyu_kendini_yikar', '“Bilgi yalnız duyu verisinden ibarettir” cümlesi duyuyla bilinemez; kendi ölçüsünü karşılamaz.', 'mantik', 'yakîn')
N('k_vuku_imkan', 'Var olan şey olabilir bir şeydir; vukû imkânı gösterir (mümteni olan var olamaz).', 'mantik', 'yakîn')
N('k_cok_vacib_cift', 'Birden fazla vâcib varsa, onlardan herhangi ikisi “iki vâcib” durumunu doğurur.', 'mantik', 'yakîn')
N('k_beka_muhtac', 'Mümkinin varlığının devamı da zâtından olmadığından, devam ettiği her an müreccihe muhtaçtır.', 'turetilmis', 'yakîn', 'sebep-ilkesi-varlik', 1, 'bekâ ihtiyacı kelâm içinde de ihtilaflıdır; hafızadan, yoklanmadı')
N('k_zulum_noksan', 'Zulüm ihtiyaç, cehalet veya acizden doğar; bunlardan hiçbiri Vâcib’de bulunamaz.', 'turetilmis', 'zan-ı gâlib', 'kemal', 1, 'zulmün tanımı muhatapla ortaklaştırılmalıdır (V.2.4.2)')
N('k_yalan_noksan', 'Yalan cehalet, acz veya ihtiyaçtan doğar; bunlardan hiçbiri Vâcib’de bulunamaz.', 'turetilmis', 'zan-ı gâlib', 'kemal', 1, 'yalanın tanımı muhatapla ortaklaştırılmalıdır')
N('k_hucre_dislama', 'Aynı suâlin hücreleri aklî hasırla birbirini dışlar: biri doğruysa öbürleri yanlıştır.', 'mantik', 'yakîn')
N('m_frekans_sans', 'Gözlenen sıklıktan eğilime (şansa) çıkarım ilmî uygulamanın dayandığı çıkarımdır (örnek: 1000 bağımsız atışta yaklaşık 750 yazı gelince paranın yazı şansı yaklaşık 3/4 sayılır); dayanağı büyük sayılar kanunudur.', 'musahede', 'zan-ı gâlib', not_='Pruss, PSR and Probability, b.2.1; çıkarımın geçerliliği tecrübî uygulamadır, muhatabın kendi kabulüdür')
N('t_bayes_aralik', 'Sebepsiz (açıklamasız) hipotez N altında gözlem dizisi E’nin olasılığı [0,1] aralığıysa, açıklayıcı hipotez H’nin sonsal olasılığı P(H|E) en az [ (1/2)^n / P(N) , 1 ] aralığını kapsar; P(N) sıfırdan büyük ve sonsuz küçük değilse n büyüdükçe alt sınır 0’a gider (Bayesçi ıraksama).', 'mantik', 'yakîn', not_='Pruss, b.2.2, s.5-6; P(E|H)=(1/2)^n, üst uç 1, alt uç ≤ (1/2)^n / P(N); koşul olarak P(E|N)=[0,1] varsayılır (p_sebepsiz_sans_yok)')
N('p_sebepsiz_sans_yok', 'Sebepsiz (açıklamasız) hipotez altında hiçbir sonucun olasılığı tanımlı değildir: ya kesin bir sayı çıkar ve açıklayıcı bir şans hipotezinden ayırt edilemez, ya hiç olasılık çıkmaz, ya da en fazla tam aralık [0,1] çıkar; açıklama olmayan yerde şans da yoktur.', 'turetilmis', 'zan-ı gâlib', 'sebepsiz-sans', 1, 'Pruss, b.2.3, s.7-8; üçlü hasır (a)(b)(c) klasik ve aralıklı olasılık çerçevesi içindedir; (c) şıkkının yalnız [0,1] vermesi gösterilmemiş, ileri sürülmüştür (G1)')
N('p_apriori_ret', 'Deneyle reddedilemeyen ve öncülü keyfî olmadan düşük tutulamayan hipotez a priori reddedilir: sebepsiz hipotezler imkânsızdır (yerel sebep ilkesi).', 'turetilmis', 'zan-ı gâlib', 'apriori-ret', 1, 'Pruss, b.2.3, s.8-10; hasmın “bilim yapılabilsin diye düşük öncül” yolu Pruss’ça tatmin edici bulunmaz fakat kapatılmış değildir (G2)')
N('t_sans_egilim', 'Şans, bir sürecin (düzenek ve kanunun) eğilimidir; sonuçlara dar bir olasılık aralığı veren hipotez bir eğilim, yani olasılıkçı bir kanun ileri sürer ve olasılıkçı açıklama sunar; hiçbir eğilim ileri sürmeyen hipotez açıklamasızdır.', 'tanim', 'yakîn', not_='Pruss’un kendi tanımları (s.1-2: şans = stokastik süreçlerin eğilimi; olasılıkçı açıklama açıklamadır); tanım muhatapla ortaklaştırılmalıdır (I.2.3); Hume’cu çıplak düzenlilik kuramı bu tanımı kabul etmez, onun için bkz. DESTEK/PRUSS_G1_G2_DENEME.md')
N('k_yoktan_sanssiz', 'Yokluk bir süreç ve düzenek değildir; yokluktan varlığa geçiş için eğilim (şans) taşıyan bir düzenek bulunamaz.', 'mantik', 'yakîn', 'yokluk-egilim', 1, 'fizik vakumu “hiçbir şey” değildir, bir fizik durumudur (V.1.4.29); vakumu “hiçbir şey” sayan hasım bu öncülü reddeder (V.1.4.84)')
N('p_esdegerlik_kureselleme', 'Düşük öncülü “aksi hâlde ayırt edilemeyen hipotezler arasında seçim keyfî olurdu” diye haklı gösteren gerekçe, küresel sebepsiz hipotezler (beş dakikalık evren, bir dakikalık geriye ışık konisi) için de aynen geçerlidir; bu hipotezler de ilmî çıkarımı aynı biçimde temelsiz bırakır.', 'turetilmis', 'zan-ı gâlib', 'kureselleme', 1, 'Pruss, b.3.2, s.12-13 (sadelik küresel sapkın hipotezleri elemez); hasım küresel tarihî çıkarımdan vazgeçerek tutarlı kalabilir (V.1.4.88)')
N('k_iddia_gerekce', 'Bir hükmü cezmen (kesin olarak) ileri süren, o hükmün gerekçesini göstermekle yükümlüdür; gerekçesiz hüküm cezmî iddia değil tevakkuftur.', 'mantik', 'yakîn', not_='V.0.2.2; sebepsizlik veya yokluk iddiası da iddiadır')
N('k_destek_hasir', 'Bir yokluk hükmünün desteği ya tecrübeden gelir (açıklamanın bulunamaması veya iç açıklamaların başarı sicilinden istikrâ) ya akıldan gelir (imkânsızlık delili veya sadelik tercihi); başka kaynak yoktur.', 'mantik', 'zan-ı gâlib', 'destek-hasir', 1, 'kaynak türlerinin sayımı hasır olarak ileri sürülmüştür; tamlığı gösterilmedi (G7)')
N('s_kaza_kurali', 'Açıklamayı bulamamak açıklama yoktur demek değildir (uçak kazası araştırmacısı örneği); hasım bunu yerel olaylarda kabul eder.', 'musahede', 'zan-ı gâlib', 'muhatap-kabulu', 1, 'Pruss, s.1 (Rescher 1995); müsellemdir, muhatabın kabulü kadardır (U27)')
N('s_parca_butun', 'Parçalardan bütüne geçiş geçerli değildir: parçaların her biri için doğru olan bütün için doğru olmak zorunda değildir (hasmın terkip safsatası itirazı).', 'musahede', 'zan-ı gâlib', 'muhatap-kabulu', 1, 'V.1.3.b.7; hasmın kendi itirazıdır; müsellemdir (U27)')
N('p_sadelik_orantisiz', 'Sadelik ölçüsü açıklamasız hipotezi her açıklayıcı hipotezden daha sade bulur; yerelde de uygulansaydı her olayı çıplak sayardı ve ilmî yöntemi yıkardı; öyleyse yalnız küresel olaya uygulanması ilkesizdir.', 'turetilmis', 'zan-ı gâlib', 'sadelik', 1, 'Pruss, s.8 (çıplak açıklamasız hipotezler daha sadedir)')
N('k_destek_ikilik', 'Bir yokluk hükmü ya çıkarımsız kabul edilir ya çıkarımla kurulur; çıkarımla kurulursa öncüller hükmü ya gerektirir ya gerektirmez; gerektirmiyorsa hükmü gerektirecek bir köprü öncül gerekir; başka hâl yoktur.', 'mantik', 'yakîn', not_='nefy–isbât; G7’yi sayımdan mantıksal ikileme çevirmek için (PRUSS_G7_HASIR.md)')
N('k_gaybi_hiss_yok', 'Duyu yalnız âlemin içindekini gözlemler; âlem dışında (Vâcib dâhil) bir şeyin yokluğu müşahede edilemez.', 'mantik', 'yakîn', not_='I.4.3.5: müşâhede edilemeyen şey duyuyla ispatlanmaz ve yokluğu da duyuyla gösterilmez')
N('k_haber_devir', 'Haber yeni destek üretmez, kaynağının desteğini devralır; devralınan destek yine bu ikilemin kollarından biridir.', 'mantik', 'yakîn', not_='I.4.5, V.1.2.5; haberin katiyeti kaynağından güçlü olamaz')
N('k_tekduzelik_aciklama', 'Hasmın elindeki tek tecrübî köprü, iç olayların açıklanmış olduğunun dışa ve bütüne taşınmasıdır (tekdüzelik); bu köprü “bütün de açıklanmıştır” sonucunu destekler, “bütün istisnadır” sonucunu desteklemez.', 'turetilmis', 'zan-ı gâlib', 'tekduzelik', 1, 'tekdüzelik varsayımı kendisi de delil istemez bir postulat sayılır; yorum tartışmalıdır (G8)')
N('k_istisna_delilsiz', '“Açıklanmışlık yalnız parçalara mahsustur, bütün istisnadır” ilkesi evvelî değildir (karşıtı tutarlıdır) ve lehine bir delil gösterilmemiştir.', 'turetilmis', 'zan-ı gâlib', 'istisna', 1, 'karşıtının tutarlı olması tek başına “delilsiz” kılmaz; sebep ilkesinin karşıtı da tutarlıdır (simetri notu: PRUSS_G7_HASIR.md b.5)')
N('k_aciklama_temelli', 'Parçalardan oluşan bir bütünde var edici açıklama ilişkisi ya temellidir (açıklanmamış en az bir parça vardır) ya temelsizdir (açıklamada geriye sonsuza gidilir veya başa dönülür); üçüncü hâl yoktur.', 'mantik', 'yakîn', not_='sıralama kuramında her ilişki ya en az bir minimal öğeye sahiptir ya da sonsuz geriye giden bir diziye veya devre sahiptir (sonlu kümede minimal öğesiz ilişki devir doğurur); kapsam: var edici (mûcid) açıklama; PRUSS_G10_ISTISNA.md')
N('k_istisna_yapi', '“Bütün açıklamasızdır fakat her parça bütünün içinden açıklanmıştır” iddiası, açıklanmamış parça bulunmadığını söyler; öyleyse var edici açıklama ilişkisi temelsizdir.', 'mantik', 'yakîn', not_='iddianın kendi öncülünden çıkar')
N('k_simetri_kirilma', 'Varlık ile yokluğun mümkine nisbeti eşitse varlığın ağır basması bir simetri kırılmasıdır; bilinen her simetri kırılmasında kırıcı (neden, şans düzeneği veya fâil) bulunmuştur (Curie ilkesi).', 'musahede', 'zan-ı gâlib', 'curie', 1, 'Pierre Curie 1894, hafızadan, yoklanmadı; yerel tecrübedir, kendiliğinden kırılma örnekleri kırıcı olarak düzenek ve dalgalanma gösterir; bütüne taşınması tekdüzelik köprüsüne bağlıdır')

